language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:  
  - '8'
script:
  - npm run test
  - npm run check-coverage
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
